site_name: Mermaid Diagram
site_description: Test Mermaid Graph Rendering
nav:
  - Diagram: README.md
plugins:
  - techdocs-core
markdown_extensions:
  pymdownx.extra:
    pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
